### PR TITLE
Ar hdf5

### PR DESCRIPTION
**Pull request by grburgess**
Adds the ability to save AnalysisResults to HDF5 files which are more flexible than FITS, thus we can expand on their content in the future. Conversion utilities are supplied to convert old saved files in FITS format. 

Does not break past result saving.

### CODE REVIEW

**Comment by grburgess** [comment]
looks like some this failed with python2...

**Comment by henrikef** [comment]
Do we still need to support python 2 at this point?

**Comment by ndilalla** [comment]
I will look into this and see if we can continue to support py27.

**Comment by grburgess** [comment]
I am happy to drop py2 support at this point.

**Comment by ndilalla** [comment]
@grburgess I dropped py27 support. Do you have any idea why it is now failing on py37 (linux)?

**Comment by grburgess** [comment]
@ndilalla I am checking.

**Comment by grburgess** [comment]
@ndilalla Ok, I fixed it... another one of these very strange byte string issues.

**Comment by ndilalla** [comment]
> @ndilalla Ok, I fixed it... another one of these very strange byte string issues.

Great, thank you! Now I can merge this one and tag the first py37-only release.

**Pull request merged**
