### PR TITLE
Updates to fermipy plugin pt 1

### PR DESCRIPTION
**Pull request by henrikef**
Generate model from fermipy output fits file.

(Todo: Check superexponential cutoff PL)

### CODE REVIEW

**Review by omodei — APPROVED** [review]
All the changes are good.

**Comment by omodei** [comment]
I tried the test locally, and the new test failed with the following exception:
`FAILED threeML/test/test_model_from_catalog.py::test_read_model_from_catalogs - ValueError: Unable to insert row because of exception in column 'Spatial_Filename':`
This failed simply calling the following command in fermipy:
`In [1]: from fermipy.gtanalysis import GTAnalysis`
`In [2]: gta=GTAnalysis("2config_Crab_4FGL.yaml",logging={'verbosity' : 3})`
`In [3]: gta.setup()`
`In [4]: gta.write_roi("roi_4FGL")`

Maybe is related to wrong fermion version? (I have fermipy 1.0.1 which is the latest available in Conda-forge)

**Review by omodei — COMMENTED** [review]
test failed locally after merging with dev

**Comment by henrikef** [comment]
Huh. I tested it locally with the new fermitools and fermipy and it was
fine. Will try and take a look at it tomorrow. Sorry!

**Comment by henrikef** [comment]
@omodei Which version of fermi tools are you using? For fermitools 2.2.x you need fermipy 2.1.x which you can get from `pip`. Unfortunately I cannot release to fermi conda myself yet.

**Pull request merged**
